extends Node
## Audio autoload: music (with crossfade and a "power down" duck), pooled SFX and the
## master volume (four steps, 0 = muted) persisted next to the locale in settings.cfg.
## Sounds are generated by tools/audio/build.py; see docs/audio-direction.md.

signal volume_changed(level: int)
## Emitted for every sound actually started (used by tests and logs).
signal sfx_played(sfx_name: String)

const SETTINGS_PATH := "user://settings.cfg"
const SETTINGS_SECTION := "audio"
const SETTINGS_KEY_VOLUME := "volume_level"
const MAX_VOLUME_LEVEL := 3
const DEFAULT_VOLUME_LEVEL := 2

const MUSIC_BUS := &"Music"
const SFX_BUS := &"SFX"
const SFX_VOICES := 10
const MUSIC_FADE := 1.2
## On the result screen the music sinks with the level's power-down.
const DUCK_DB := -9.0
const SILENT_DB := -60.0

const MUSIC := {
	"scanning_table": preload("res://audio/music/scanning_table.ogg"),
	"exposure": preload("res://audio/music/exposure.ogg"),
}
const SFX := {
	"launch": preload("res://audio/sfx/launch.wav"),
	"wall_hit": preload("res://audio/sfx/wall_hit.wav"),
	"fizz": preload("res://audio/sfx/fizz.ogg"),
	"goal": preload("res://audio/sfx/goal.ogg"),
	"out_of_balls": preload("res://audio/sfx/out_of_balls.ogg"),
	"target_met": preload("res://audio/sfx/target_met.ogg"),
	"ui_click": preload("res://audio/sfx/ui_click.wav"),
	"ui_hover": preload("res://audio/sfx/ui_hover.wav"),
	"ui_confirm": preload("res://audio/sfx/ui_confirm.wav"),
	"rotate": preload("res://audio/sfx/rotate.wav"),
	"empty": preload("res://audio/sfx/empty.wav"),
}
## Minimum seconds between two starts of the same sound (avoids machine-gun stacking).
const MIN_INTERVAL := {
	"wall_hit": 0.04,
	"fizz": 0.25,
	"rotate": 0.035,
	"ui_hover": 0.08,
}
## Wall hits are tuned along D Dorian from D5: the scale degree rises with the wall's
## multiplier and with the ball's speed, so a fast ball off a x2.4 wall rings highest.
const DORIAN_STEPS := [0, 2, 3, 5, 7, 9, 10, 12, 14, 15]
const BOOST_LOW := 1.2
const DEGREES_PER_BOOST := 5.0
const BASE_SPEED := 400.0
const MAX_SPEED_DEGREES := 3

var volume_level: int = DEFAULT_VOLUME_LEVEL
var _muted_from: int = DEFAULT_VOLUME_LEVEL
var _voices: Array[AudioStreamPlayer] = []
var _next_voice := 0
var _last_played := {}
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _active_music: AudioStreamPlayer
var _current_music := ""
var _music_tween: Tween
var _ducked := false


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in SFX_VOICES:
		var voice := AudioStreamPlayer.new()
		voice.bus = SFX_BUS
		add_child(voice)
		_voices.append(voice)
	_music_a = _new_music_player()
	_music_b = _new_music_player()
	_active_music = _music_b
	_set_volume_level(_load_volume_level(), false)


# Stops playbacks on quit so the audio server can release the streams before shutdown.
func _exit_tree() -> void:
	for player in _voices + [_music_a, _music_b]:
		player.stop()
		player.stream = null


func _new_music_player() -> AudioStreamPlayer:
	var player := AudioStreamPlayer.new()
	player.bus = MUSIC_BUS
	player.volume_db = SILENT_DB
	add_child(player)
	return player


# --- SFX -----------------------------------------------------------------------------

func play(sfx_name: String, pitch: float = 1.0, volume_db: float = 0.0) -> void:
	if not SFX.has(sfx_name):
		push_error("Unknown sound %s" % sfx_name)
		return
	var now := Time.get_ticks_msec() / 1000.0
	if now - float(_last_played.get(sfx_name, -1.0)) < float(MIN_INTERVAL.get(sfx_name, 0.0)):
		return
	_last_played[sfx_name] = now
	var voice := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % _voices.size()
	voice.stream = SFX[sfx_name]
	voice.pitch_scale = pitch
	voice.volume_db = volume_db
	voice.play()
	sfx_played.emit(sfx_name)


## A ball bounced off a magnet wall with multiplier `boost` at `speed` px/s.
func play_wall_hit(boost: float, speed: float) -> void:
	var degree := roundi((boost - BOOST_LOW) * DEGREES_PER_BOOST)
	degree += clampi(int(log(maxf(speed, 1.0) / BASE_SPEED) / log(2.0)), 0, MAX_SPEED_DEGREES)
	degree = clampi(degree, 0, DORIAN_STEPS.size() - 1)
	var semitones: int = DORIAN_STEPS[degree]
	var loudness := clampf(-6.0 + 2.0 * log(maxf(speed, 1.0) / BASE_SPEED) / log(2.0), -6.0, 0.0)
	play("wall_hit", pow(2.0, semitones / 12.0), loudness)


# --- Music ---------------------------------------------------------------------------

## Crossfades to `track` (no-op if it is already playing). Restores an active duck.
func play_music(track: String) -> void:
	if not MUSIC.has(track):
		push_error("Unknown music %s" % track)
		return
	if track == _current_music:
		duck_music(false)
		return
	_current_music = track
	_ducked = false
	var outgoing := _active_music
	_active_music = _music_b if outgoing == _music_a else _music_a
	_active_music.stream = MUSIC[track]
	_active_music.volume_db = SILENT_DB
	_active_music.play()
	_fade_music(0.0)
	GameLogger.info("Music: %s" % track, "Audio")


## Sinks the current track under the result screen (true) or brings it back (false).
func duck_music(ducked: bool) -> void:
	if ducked == _ducked:
		return
	_ducked = ducked
	_fade_music(DUCK_DB if ducked else 0.0)


## Fades the active track to `active_db` and the other player out (then stops it).
func _fade_music(active_db: float) -> void:
	if _music_tween:
		_music_tween.kill()
	var idle := _music_b if _active_music == _music_a else _music_a
	_music_tween = create_tween().set_parallel()
	_music_tween.tween_property(_active_music, "volume_db", active_db, MUSIC_FADE)
	_music_tween.tween_property(idle, "volume_db", SILENT_DB, MUSIC_FADE)
	_music_tween.chain().tween_callback(_stop_silent_music)


func _stop_silent_music() -> void:
	for player in [_music_a, _music_b]:
		if player.volume_db <= SILENT_DB + 0.1:
			player.stop()


# --- Volume --------------------------------------------------------------------------

## Steps the volume down: 3 -> 2 -> 1 -> off -> 3 (the HUD "Sound" control).
func cycle_volume() -> void:
	var next := volume_level - 1
	if next < 0:
		next = MAX_VOLUME_LEVEL
	_set_volume_level(next, true)


func toggle_mute() -> void:
	if volume_level == 0:
		_set_volume_level(maxi(_muted_from, 1), true)
	else:
		_muted_from = volume_level
		_set_volume_level(0, true)


func _set_volume_level(level: int, save: bool) -> void:
	volume_level = clampi(level, 0, MAX_VOLUME_LEVEL)
	var master := AudioServer.get_bus_index(&"Master")
	AudioServer.set_bus_mute(master, volume_level == 0)
	var linear := float(volume_level) / MAX_VOLUME_LEVEL
	AudioServer.set_bus_volume_db(master, linear_to_db(linear) if volume_level > 0 else SILENT_DB)
	if save:
		_save_volume_level(volume_level)
	volume_changed.emit(volume_level)


func _unhandled_key_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo and event.keycode == KEY_M:
		toggle_mute()
		play("ui_click")


func _load_volume_level() -> int:
	var config := ConfigFile.new()
	if config.load(SETTINGS_PATH) != OK:
		return DEFAULT_VOLUME_LEVEL
	return clampi(int(config.get_value(SETTINGS_SECTION, SETTINGS_KEY_VOLUME, DEFAULT_VOLUME_LEVEL)), 0, MAX_VOLUME_LEVEL)


func _save_volume_level(level: int) -> void:
	var config := ConfigFile.new()
	config.load(SETTINGS_PATH)
	config.set_value(SETTINGS_SECTION, SETTINGS_KEY_VOLUME, level)
	var err := config.save(SETTINGS_PATH)
	if err != OK:
		GameLogger.error("Failed to save volume (error %d)" % err, "Audio")
